### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by kamfosica** [YamikaniSita/binary-calculator#1]
https://github.com/YamikaniSita/binary-calculator/blob/f5485b164520b0f06234363641ceaa6d6b9349d8/js/ip.js#L88

I think that line should be 

```javascript
this.getClass() === 'D' || this.getClass() === 'E'
```
since the class can't be **D** and **E** at the same time.

Also, you can use regular expression to both validate and extract your octets that way.

Cheers

**Comment by YamikaniSita** [comment]
Yes that's true.. thank you, will clear that.
